#linea de comentarios



"salto de lineas con comentarios"""
"en varias lineas."""
" en diferente formato"


#operadores aritmeticos

a = 8   
b = 2

suma = a + b
print (f"LA SUMA DE A + B ES : {suma}")
resta = a - b
print (f"LA RESTA DE A - B ES : {resta}")
multiplicacion = a * b
print (f"LA MULTIPLICACION DE A * B ES: {multiplicacion}")
division = a / b
print (f"LA DIVISION ENTRE A / B ES : {division}")
modulo = a % b
print (f"EL MODULO (RESTO DE DIVISION) ENTRE A % B ES : {modulo}")
potencia = a ** b 
print (f"LA POTENCIA DE A ELEVADO A B ES : {potencia}")
div_entera = a // b
print (f"LA DIVISION ENTERA ENTRE A // B ES: {div_entera}")

#OPERADORES RELACIONALES

x = True
y = False

func_and = x and y
print (f"EL OPERADOR AND DE X(true), Y (false) ES: {func_and}")

func_or = x or y
print (f"EL OPERADOR OR DE X(true), Y (false) ES: {func_or}")

func_not = not y
print (f"EL OPERADOR NOT DE Y (false) ES: {func_not}")


# operadores de comparación

c = 5

mayor_que = a > b
menor_que = a < b
igual_que = a == b
distinto_de = a != b
mayor_o_igual_que = a >= c
menor_o_igual_que = b <= a

print(f"A ES MAYOR QUE B? : {mayor_que}")
print(f"A ES MENOR QUE B? : {menor_que}")
print(f"A ES IGUAL QUE B? : {igual_que}")
print(f"A ES DISTINTO DE B? : {distinto_de}")
print(f"A ES MAYOR O IGUAL QUE B? : {mayor_o_igual_que}")
print(f"A ES MENOR O IGUAL QUE B? : {menor_o_igual_que}")






